# Generated by Django 3.1.4 on 2022-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifications',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
