# Generated by Django 3.1.4 on 2023-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_verifications_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default='Sin informacion', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='municipality',
            field=models.CharField(default='Sin declarar', max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='provincie',
            field=models.CharField(default='Sin registrar', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='catastral_reference',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
